SELECT *
FROM (SELECT cp.COMPANY_NAME,cp.COMPANY_CITY,sum(od.ORD_AMOUNT) as SUMMARY
FROM company cp
JOIN agents ag
ON ag.COMPANY_ID=cp.COMPANY_ID
JOIN orders od
ON od.AGENT_CODE=ag.AGENT_CODE
GROUP BY cp.COMPANY_NAME,cp.COMPANY_CITY) s
ORDER BY SUMMARY DESC
LIMIT 1